### ISSUE TITLE
[BUG] Unexpected error occurred after startup FanControl Commander Pro

### ISSUE THREAD

**Issue by Scuba0070** [iJacks1980/FanControl.CommanderPRO#21]
**Describe the bug**
After I installed the corsair commander pro plug in i get an error after startup of FanControl that says and unexpected error has occurred and has been added to the log file. 

Here is a paste of the log file:
10/30/2022 9:49:07 AM: System.InvalidOperationException
   at FanControl.Domain.ApplicationContext.ShowMainWindow()
   at FanControl.App.<>c__DisplayClass20_0.<<Logger_OnLogForUser>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.ApplicationContext.<InvokeAsync>d__10.MoveNext()
10/30/2022 10:03:44 AM: Corsair Commander CORE XT could not initialize or has no sensors.
Corsair Commander CORE could not initialize or has no sensors.
10/30/2022 10:03:44 AM: Unhandled exception in FanControl v1.0.0.0
10/30/2022 10:03:45 AM: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.InvalidOperationException
   at FanControl.Domain.ApplicationContext.ShowMainWindow()
   at FanControl.App.<>c__DisplayClass20_0.<<Logger_OnLogForUser>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.ApplicationContext.<InvokeAsync>d__10.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException
   at FanControl.Domain.ApplicationContext.ShowMainWindow()
   at FanControl.App.<>c__DisplayClass20_0.<<Logger_OnLogForUser>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.ApplicationContext.<InvokeAsync>d__10.MoveNext()<---

10/30/2022 10:03:45 AM: System.InvalidOperationException
   at FanControl.Domain.ApplicationContext.ShowMainWindow()
   at FanControl.App.<>c__DisplayClass20_0.<<Logger_OnLogForUser>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.ApplicationContext.<InvokeAsync>d__10.MoveNext()

Corsair Commander PRO

**Comment by jwatte** [comment]
I get the same problem.
I only have a Commander Pro, not a CORE or CORE XT.
And then it didn't update the fan curve for my pump, and the CPU overheated ...

  10/30/2022 1:51:37 PM: Corsair Commander CORE XT could not initialize or has no sensors.
  Corsair Commander CORE could not initialize or has no sensors.
  10/30/2022 1:51:38 PM: Unhandled exception in FanControl v1.0.0.0
  10/30/2022 1:51:39 PM: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.InvalidOperationException
     at FanControl.Domain.ApplicationContext.ShowMainWindow()
     at FanControl.App.<>c__DisplayClass20_0.<<Logger_OnLogForUser>b__0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at FanControl.Domain.ApplicationContext.<InvokeAsync>d__10.MoveNext()
     --- End of inner exception stack trace ---
  ---> (Inner Exception #0) System.InvalidOperationException
     at FanControl.Domain.ApplicationContext.ShowMainWindow()
     at FanControl.App.<>c__DisplayClass20_0.<<Logger_OnLogForUser>b__0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at FanControl.Domain.ApplicationContext.<InvokeAsync>d__10.MoveNext()<---
