### ISSUE TITLE
Corsair H150i Capellix fans not detected

### ISSUE THREAD

**Issue by irlrobins** [iJacks1980/FanControl.CommanderPRO#3]
**Describe the bug**
When running the sensors detection, the fans connected to my H150i are not detected in FanControl

**To Reproduce**
1) Did a clean uninstall of iCUE
2) Installed FanControl version V110 into C:\Program Files\FanControl
3) Created a subfolder called Plugins
4) Installed FanControl.CommanderPro.dll in plugins folder, unblocked file
5) Launched FanControl as administrator 
6) Plugin detected and enabled:
![image](https://user-images.githubusercontent.com/104267065/164943796-bb43ce85-318a-46b5-b997-75991b7416e2.png)
7) The 6 ML120 fans connected to Commander Core are not detected in FanControl after running initial setup process:
![image](https://user-images.githubusercontent.com/104267065/164943819-19171274-1f59-40ee-a118-b2a7cef8e975.png)

No CommanderPRO.err.log file created.

**Expected behavior**
The 6 ML120 fans are detected and available to control via Fan Controls

**Specs**
- Windows 10
- FanControl V110
- FanControl.CommanderPRO V1.0.0
- iCUE H150i ELITE CAPELLIX
- 6 x ML120 Elite fans, all connected to Commander Core

**Comment by iJacks1980** [comment]
Hi irlrobins,

This is caused by the plugin looking for the Commander PRO hardware only, not the Commander CORE.

I don't have a core to test anything with, but would you be willing to test new versions for me?

For starters can you look in your Windows Device Manager, then change the View to "Devices by Container".  It should look a little like below:

![image](https://user-images.githubusercontent.com/76005029/164945471-3a2d14fb-60c4-46fd-ac09-e512fe1fa6de.png)

On my system I see a device group called Commander PRO - I'm hoping you will see something similar like Commander CORE.

Let me know the exact name and I'll get a new build that will try talking to the CORE device for you.

**Comment by irlrobins** [comment]
I'd be delighted to help test. Here is what I have in Device Manager:
![image](https://user-images.githubusercontent.com/104267065/164945594-e7092506-1acb-45e6-b27d-f185f27b8562.png)

**Comment by iJacks1980** [comment]
So, a very much rushed beta release ;)

This version should only be for testing as it saves a lot of trace data regarding your HID devices (to a local file only) - this will be removed from a proper 1.0.1 release.

When the plugin is initialised it should save a file in your Fan Control folder called "CommanderPRO.trc.log" - it's just a text file but right now it will list every HID device on your computer (so every USB connected device).  In that file there should be an entry similar to this:

Found device: Commander PRO
	Vendor ID: 6940
	Product ID: 3088
	Manufacturer: Corsair

Of course, yours should have the Commander CORE :)  Let me know the details it lists, so I can the code back to getting device by ID rather than by name.

Hopefully they kept the protocol the same between the PRO and CORE - in which case Fan Control should see your fans and be able to control them.

[FanControl.CommanderPro.dll.zip](https://github.com/iJacks1980/FanControl.CommanderPRO/files/8548617/FanControl.CommanderPro.dll.zip)

**Comment by irlrobins** [comment]
I don't think that worked as expected. The CommanderPRO.trc.log was created and I could see entries in it relating to my mouse, keyboard, etc. But nothing for Commander. And then in log.txt file was this error:


23/04/2022 22:26:10: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.CommanderPro.CommanderPro.Connect()
   at FanControl.CommanderPro.Plugin.Initialize()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
23/04/2022 22:26:10: Corsair Commander PRO could not initialize.

**Comment by iJacks1980** [comment]
ok, so that's irritating.  This version also probably won't work, but I've wrapped up the connect method to log any connect errors (should have done that in the first place!)

This version tries to do the same, but will log any errors when connecting to the error log.  At the very least it will state exactly where it explodes!

I guess Corsair don't want to make this too easy!

[FanControl.CommanderPro.zip](https://github.com/iJacks1980/FanControl.CommanderPRO/files/8548655/FanControl.CommanderPro.zip)

**Comment by irlrobins** [comment]
I used USBDeview to get the info I think you need:
Device Name: CORSAIR iCUE Commander CORE
Vendor ID 1b1c
Product ID 0c1c

I needed to reinstall iCUE to get this to work, otherwise the USB device (the commander core) doesn't register

**Comment by irlrobins** [comment]
Scrap that last comment. I reran the first test plugin you gave me with iCUE installed and was able to get the data:
Found device: CORSAIR iCUE Commander CORE
	Vendor ID: 6940
	Product ID: 3100
	Manufacturer: Corsair

But error logged in CommanderPRO.err.log
System.IO.IOException: Can't write to this device.
   at HidSharp.Platform.Windows.WinHidStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at FanControl.CommanderPro.CommanderPro.GetFanMask()

Do you want me to try with the second test plugin or are you good now?

**Comment by iJacks1980** [comment]
Give the second one a try (without iCUE if possible), I _think_ it will have the same issue (can't write to device).

I can think of two reasons for this:

1. iCUE fully locks the device by taking exclusive ownership.
2. The Commander CORE requires a driver installed by iCUE in order to be seen/accessed.  I really hope it's the 1st one.

I may need to grab a CORE to fully work this one out, but give that 2nd version a go and see what it puts in the trace log (delete the error and trace logs first, they are only appended to so would still be full of previous sessions data).

**Comment by irlrobins** [comment]
Running with iCUE:
trc file has:
Searching for HID Devices
Found device: \\?\hid#vid_1532&pid_0099&mi_01&col03#9&a94cb4e&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
	device name: Razer Basilisk V3
	product name: Razer Basilisk V3
	Vendor ID: 5426
	Product ID: 153
	Manufacturer: Razer

Found device: \\?\hid#vid_1532&pid_0099&mi_00&col03#a&34f016df&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
	device name: 
	product name: 
	Vendor ID: 5426
	Product ID: 153
	Manufacturer: 

err log has:
System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.CommanderPro.CommanderPro.Connect()

Will rerun without iCUE installed next

**Comment by irlrobins** [comment]
And running without iCUE installed:

trc file has:
Searching for HID Devices
Found device: \\?\hid#vid_1532&pid_0099&mi_00#9&1dc4e78c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
	device name: Razer Basilisk V3
	product name: Razer Basilisk V3
	Vendor ID: 5426
	Product ID: 153
	Manufacturer: Razer

Found device: \\?\hid#vid_1532&pid_0099&mi_01&col01#9&a94cb4e&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd
	device name: Razer Basilisk V3
	product name: Razer Basilisk V3
	Vendor ID: 5426
	Product ID: 153
	Manufacturer: Razer

Found device: \\?\hid#vid_1532&pid_0099&mi_03#9&1bcb6d2e&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
	device name: Razer Basilisk V3
	product name: Razer Basilisk V3
	Vendor ID: 5426
	Product ID: 153
	Manufacturer: Razer

Found device: \\?\hid#vid_1532&pid_025e&mi_00#9&1e89cfc6&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd
	device name: Razer Cynosa V2
	product name: Razer Cynosa V2
	Vendor ID: 5426
	Product ID: 606
	Manufacturer: Razer

Found device: \\?\hid#vid_1532&pid_0099&mi_02#9&89b50f0&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd
	device name: Razer Basilisk V3
	product name: Razer Basilisk V3
	Vendor ID: 5426
	Product ID: 153
	Manufacturer: Razer

Found device: \\?\hid#vid_1532&pid_0099&mi_00&col03#a&34f016df&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
	device name: 
	product name: 
	Vendor ID: 5426
	Product ID: 153
	Manufacturer: 

err log has:
System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.CommanderPro.CommanderPro.Connect()

**Comment by iJacks1980** [comment]
Hmmm, interesting.  Seems you have a device that really _really_ doesn't want to be identified!

Ok, final attempt for tonight.  As you were able to find the product id lets just bypass all the device detection and go direct (as the original version did).

Trace file should only have a single entry in it with this version.

[FanControl.CommanderPro.zip](https://github.com/iJacks1980/FanControl.CommanderPRO/files/8548719/FanControl.CommanderPro.zip)

**Comment by irlrobins** [comment]
Some more info that might help. With iCUE installed, if I run USBDeview, the Commander Core is only listed when iCUE is running. As soon as I exit iCUE, the commander drops off the list of USB devices

**Comment by iJacks1980** [comment]
Is you Commander CORE this specific one: https://www.corsair.com/uk/en/Categories/Products/Accessories-%7C-Parts/CORSAIR-iCUE-COMMANDER-CORE-XT-Smart-RGB-Lighting-and-Fan-Speed-Controller/p/CL-9011112-WW

**Comment by irlrobins** [comment]
> Is you Commander CORE this specific one: https://www.corsair.com/uk/en/Categories/Products/Accessories-%7C-Parts/CORSAIR-iCUE-COMMANDER-CORE-XT-Smart-RGB-Lighting-and-Fan-Speed-Controller/p/CL-9011112-WW

No, it's the none XT one that comes as part of the Capellix AIO. Similar, but different. 

![image](https://user-images.githubusercontent.com/104267065/164948235-e5ebb655-2527-432b-b789-41a8cb157dc3.png)

**Comment by irlrobins** [comment]
Running the latest plugin results

trc: Found HID Device: CORSAIR iCUE Commander CORE
err: System.IO.IOException: Can't write to this device.
   at HidSharp.Platform.Windows.WinHidStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at FanControl.CommanderPro.CommanderPro.GetFanMask()

Same result each time for
1) iCUE installed and running
2) iCUE installed but not running
3) iCUE not installed

**Comment by iJacks1980** [comment]
I think I need to get my hands on one of those controllers.  It's not the same as the PRO at all :(

I have found a C# wrapper for the official iCUE SDK - so I will look into that first - sadly it seems that Corair only made Capellix in sizes larger than my case, so getting an entire AIO is out of the question - shame, my NZXT one is getting rather old and is ripe rof replacement.

**Comment by irlrobins** [comment]
Well let me know if I can help in any way in the mean time!

**Comment by artjsalina5** [comment]
I am having the same exact issue where the commander core that comes with my AIO is not getting picked up in fancontrol. Eventually as I move onto a custom loop, using the Temp sensor in this commander core would be the optimal way to configure my fans. I greatly appreciate your hard work on this.

**Comment by iJacks1980** [comment]
[Beta version](https://github.com/iJacks1980/FanControl.CommanderPRO/releases/tag/v1.0.2a) with partial Commander CORE support has been released.

**Comment by irlrobins** [comment]
Testing 1.0.2 version this morning. I exited iCUE application, and stopped all Corsair services. I updated the FanControl.CommanderPro.dll file in the Plugins folder and unblocked it. I deleted all previous userConfig log files and ran FanControl.exe as admin. 

Sensor settings:
![image](https://user-images.githubusercontent.com/104267065/165913258-f0488db8-3110-4afd-93f4-e7a5592f0fed.png)

When FanControl ran it's auto config functions, I got this error message:
![image](https://user-images.githubusercontent.com/104267065/165913361-006561f7-35c0-4e7e-ad7d-4dd3f9a69527.png)

Only my GPU fans are detected:

![image](https://user-images.githubusercontent.com/104267065/165913453-df667d56-87a6-4d4b-8199-5a0657aae7e0.png)

No case fans connected to Core detected. Error and trace logs attached. 
[CommanderCORE.trc.log](https://github.com/iJacks1980/FanControl.CommanderPRO/files/8589494/CommanderCORE.trc.log)
[CommanderCORE.err.log](https://github.com/iJacks1980/FanControl.CommanderPRO/files/8589495/CommanderCORE.err.log)

**Comment by iJacks1980** [comment]
The initial error messages are caused by Fan Control not removing it's configuration when removing a sensor, on future runs that shouldn't happen.

Did you reboot after uninstalling iCUE?

I've had to exit and re-run Fan Control after removing the Motherboard sensors (or even when updating the plugin DLL), on the second and subsequent runs it's then worked as expected.  I know that the LibreHardwareMonitorLib talks to the Commander CORE in a limited fashion, and it seems to lock the device - even turning the sensor off it doesn't release it.  But a fresh start appears to prevent it from grabbing the device in the first place.

**Comment by irlrobins** [comment]
Yep, restart and relaunch of FanControl and I get the same result/errors.

**Comment by iJacks1980** [comment]
Did you save the config after exiting Fan Control?  The errors in your screenshot are because the user config json is listing sensors that are no longer found.

Anyway, give this application a quick go - maybe a few goes - just press Enter to exit.  It calls the same code that the Fan Control plugin does, but lists the data in a console.

If it always (multiple runs) comes back with Bad firmware data then something else on your system has locked the Commander CORE device.  Otherwise it should, every second, list the fan channels and temperatures.

[ConsoleApp1.zip](https://github.com/iJacks1980/FanControl.CommanderPRO/files/8595483/ConsoleApp1.zip)

**Comment by irlrobins** [comment]
_Bravely runs an .exe file from some random person on the internet_ ;)

Failed:
![image](https://user-images.githubusercontent.com/104267065/166093856-8035c126-5286-46b8-9f86-321f6e05b89e.png)

Logs:
[CommanderCORE.trc.log](https://github.com/iJacks1980/FanControl.CommanderPRO/files/8596240/CommanderCORE.trc.log)
[CommanderCORE.err.log](https://github.com/iJacks1980/FanControl.CommanderPRO/files/8596242/CommanderCORE.err.log)

**Comment by irlrobins** [comment]
I ran Process Explorer to see what might be locking the Commander, but there doesn't appear to be anything:

![image](https://user-images.githubusercontent.com/104267065/166119211-8a445eef-41fd-488a-837e-cda4be9c2bee.png)

![image](https://user-images.githubusercontent.com/104267065/166119225-b52b99cc-583d-4751-a24c-8c644abd0df7.png)

**Comment by irlrobins** [comment]
And then amazingly enough, after I reinstall iCUE and run it, I got app to work:

![image](https://user-images.githubusercontent.com/104267065/166119593-d8640ce2-5f26-4ca5-bc80-17b9a4bcdbc8.png)
[CommanderCORE.trc.log](https://github.com/iJacks1980/FanControl.CommanderPRO/files/8597654/CommanderCORE.trc.log)

**Comment by artjsalina5** [comment]
Still no temperature sensor, and as for fans, I have DC fans and it wont pick up their speed. I'm beginning to think that the commander core doesnt work for dc fans

**Comment by iJacks1980** [comment]
Yes the RGB will go dark - no way around that.  The Commander CORE has two modes of operation.  Hardware and Software.

In Hardware mode (ie before OS and iCUE is loaded) you get no control, at best you can read the firmware data.  In order to get fan details it has to be in Software mode.  And this is where Corsair are a pain.  In Software mode the RGB is controlled by...yup...software.

The reason you are seeing random data above is because iCUE is installed and running - I can only guess that iCUE unlocked the device so it could at least be read, but when doing that it's all down to timing - and my code is then fighting iCUE, so when I ask for data there is a checksum, when you get no data it's because the checksum does not match.

artjsalina5, what Commander device do you have?  The trace file should show the exact device and Firmware version.  I do know that Corsair changed the protocol in 2.10.219 - which is what I have.  If you have the Commander CORE XT then it's a bit of a crap shoot as it is a different device, and does have a different protocol.

I doubt it will pick up speed data from DC based fans as the CORE devices were designed for PWM ones only - your DC fans probably run at 100% all the time.

**Comment by artjsalina5** [comment]
Plugin initializing
Attempting to connect to Commander CORE
Connected to device: CORSAIR iCUE Commander CORE
Attempting to get Commander CORE firmware version
Commander CORE Firmware v2.10.219

I already moved my fans over to my mobo, now just need a way for the temp
sensor in the commander core to feed to fancontrol so I can control speed
based on coolant temp

**Comment by irlrobins** [comment]
> In Hardware mode (ie before OS and iCUE is loaded) you get no control, at best you can read the firmware data. In order to get fan details it has to be in Software mode. 

I can get fan and temp data using the ConsoleApp (although most executions fail with firmware error) when iCUE is not running and pump is in hardware mode (I have different colour profiles for s/w vs h/w so can tell what mode it's in).

**Comment by iJacks1980** [comment]
Just a quick update, I **_think_** I have found why it is doing this.  Code is not ready to be released - it's very late and I have work in the morning - but I am hopeful to get a new version out tomorrow evening that will work **_without_** iCUE installed.

**Comment by iJacks1980** [comment]
[Latest beta](https://github.com/iJacks1980/FanControl.CommanderPRO/releases/tag/v1.0.3a) should resolve the wonky device connection!

**Comment by artjsalina5** [comment]
Excellent work! Wow. I can now see the temperature reading in FanControl, however it pegs to 0 every second or so, not very consistent.

**Comment by iJacks1980** [comment]
> Excellent work! Wow. I can now see the temperature reading in FanControl, however it pegs to 0 every second or so, not very consistent. Edit: I helped the spazzing out by disabling rgb control in iCue, however it still pegs to 0 sometimes and fancontrol must be restarted to get the reading again.

Is this with or without iCUE installed?

**Comment by artjsalina5** [comment]
A restart seemingly resolved it. I have icue installed, but have disabled
it to start with windows.

**Comment by irlrobins** [comment]
> Excellent work! Wow. I can now see the temperature reading in FanControl, however it pegs to 0 every second or so, not very consistent. Edit: I helped the spazzing out by disabling rgb control in iCue, however it still pegs to 0 sometimes and fancontrol must be restarted to get the reading again.

I see the same experience with iCUE running, reads temp but every so often reads 0C which cases fans to start to drop speed before picking back up again when actual temp is restored, which creates an annoying ambient noise as the fans speeds jump up and down. I've got all the fans connected to motherboard headers and not the Commander Core as that's the only way currently to control them.

**Comment by iJacks1980** [comment]
Yes, currently if iCUE is running (or even installed) it will cause data to be lost.  Right now I've not released a binary that allows fan control via the Commander CORE, still working on the updated protocol.

**Comment by irlrobins** [comment]
Makes sense, but when I quit iCUE and run the plugin in Fan Control, the RGB goes black. So pros and cons with either approach. Obviously still in beta, but great progress so far, well done Steve.

**Comment by iJacks1980** [comment]
Sadly the RGB might be beyond what I can do, as the way the device works in order to get control of the fans (which I am still struggling with) you have to put the device into "Software mode".  The thing is in this mode it expects a constant stream of data to say what the RGB should be doing.  What I need is a USB interceptor, so I can watch **exactly** what iCUE sends to the device - bit of of my budget right now though.

Anyway, there is a new [version](https://github.com/iJacks1980/FanControl.CommanderPRO/releases/tag/v1.0.4) which supports the latest FanControl release.

**Comment by irlrobins** [comment]
Does Wireshark not provide USB packet sniffing?

**Comment by Kazz3r24** [comment]
Hi! Loving this app! I just got this AIO and was looking to get it set up through FanControl. I realize there's the question of RGB working or not with this. Currently my iCUE is receiving it's RGB instructions from Synapse via ChromaControl - does implementing RGB this way make a difference as to whether or not RGB will still work if I was to use this plugin?

I suppose I could always "try it and see" but I don't know if reverting the change is as simple as deleting the .dll and restarting FanControl or not.
